sudo: required
language: c++
services:
  - docker

before_install:
  - docker pull nestal/hearty_rabbit_dev
  - git submodule update --init --recursive

script:
  - make -f automation/Makefile BUILD_NUMBER=$TRAVIS_BUILD_NUMBER

deploy:
  provider: packagecloud
  username: me@nestal.net
  repository: hearty_rabbit
  token: "${PACKAGECLOUD_TOKEN}"
  dist: "centos/7"
  package_glob: "*.rpm"
  skip_cleanup: true
