sudo: required
env:
  - OS_TYPE=centos OS_VERSION=7
language: python
python:
  - "3.6"

services:
  - docker
  - redis-server

before_install:
  - docker pull nestal/hearty_rabbit_dev
  - git submodule update --init --recursive

install:
  - pip install --upgrade pip
  - pip install requests Pillow

script:
  - docker build -t nestal/hearty_rabbit --network="host" .
  - ./automation/start_tests

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD";
    docker tag nestal/hearty_rabbit nestal/hearty_rabbit:$TRAVIS_BUILD_NUMBER;
    docker tag nestal/hearty_rabbit nestal/hearty_rabbit:latest;
    docker push nestal/hearty_rabbit;
    echo "Pushed docker image to hub";
    fi
