sudo: required
env:
  - OS_TYPE=centos OS_VERSION=7
language: c++
services:
  - docker
  - redis-server

before_install:
  - docker pull nestal/hearty_rabbit_dev
  - git submodule update --init --recursive

script:
  - docker build -t hearty_rabbit --network="host" .
