sudo: required
env:
  - OS_TYPE=centos OS_VERSION=7
language: python
python:
  - "3.6"

services:
  - docker
  - redis
  - postgresql

before_install:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD" nestal.azurecr.io
  - docker pull nestal.azurecr.io/hearty_rabbit_dev
  - git submodule update --init --recursive

before_script:
  - psql -f ./init.sql -U postgres

install:
  - pip install --upgrade pip
  - pip install requests Pillow numpy redis

script:
  - docker build -t nestal.azurecr.io/hearty_rabbit --network="host" --build-arg BUILD_NUMBER=$TRAVIS_BUILD_NUMBER .
  - ./automation/start_tests

after_success:
  # Never push docker image if it's just a merge request
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      if [ "$TRAVIS_BRANCH" == "master" ]; then
        echo "build for master branch $TRAVIS_BRANCH";
        docker tag nestal.azurecr.io/hearty_rabbit nestal.azurecr.io/hearty_rabbit:$TRAVIS_BUILD_NUMBER;
      fi;
      if [ "$TRAVIS_BRANCH" == "develop" ] || [ "$TRAVIS_BRANCH" == "master" ]; then
        docker tag nestal.azurecr.io/hearty_rabbit nestal.azurecr.io/hearty_rabbit:$TRAVIS_BRANCH;
      fi;
      docker push nestal.azurecr.io/hearty_rabbit;
      echo "Pushed docker image to hub";
    fi;
