sudo: required
env:
  - OS_TYPE=centos OS_VERSION=7
language: python
python:
  - "3.6"

services:
  - docker
  - redis-server

before_install:
  - docker pull nestal/hearty_rabbit_dev
  - git submodule update --init --recursive

install:
  - pip install --upgrade pip
  - pip install requests Pillow numpy redis

script:
  - docker build -t nestal/hearty_rabbit --network="host" --build-arg BUILD_NUMBER=$TRAVIS_BUILD_NUMBER .
  - ./automation/start_tests

after_success:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
  - if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_BRANCH" == "release_v0.1" ]; then
    docker tag nestal/hearty_rabbit nestal/hearty_rabbit:$TRAVIS_BUILD_NUMBER;
    fi;
  - docker tag nestal/hearty_rabbit nestal/hearty_rabbit:$TRAVIS_BRANCH
  - docker push nestal/hearty_rabbit
  - echo "Pushed docker image to hub"
