sudo: required
env:
  - OS_TYPE=centos OS_VERSION=7
language: generic
services:
  - docker
  - redis-server

before_install:
  - docker pull nestal/hearty_rabbit_dev
  - git submodule update --init --recursive

# TODO: need to add automated tests here
script:
  - docker build -t nestal/hearty_rabbit --network="host" .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD";
    docker tag nestal/hearty_rabbit nestal/hearty_rabbit:$TRAVIS_BUILD_NUMBER;
    docker tag nestal/hearty_rabbit nestal/hearty_rabbit:latest;
    docker push nestal/hearty_rabbit;
    echo "Pushed docker image to hub";
    fi
