sudo: required
env:
  - OS_TYPE=centos OS_VERSION=7
language: python
python:
  - "3.6"

services:
  - docker
  - redis-server

before_install:
  - docker pull nestal/hearty_rabbit_dev
  - git submodule update --init --recursive

install:
  - pip install --upgrade pip
  - pip install requests Pillow numpy redis

script:
  - docker build -t nestal/hearty_rabbit --network="host" --build-arg BUILD_NUMBER=$TRAVIS_BUILD_NUMBER .
  - ./automation/start_tests

after_success:
  # Never push docker image if it's just a merge request
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD";
      if [ "$TRAVIS_BRANCH" == "master" ]; then
        echo "build for master branch $TRAVIS_BRANCH";
        docker tag nestal/hearty_rabbit nestal/hearty_rabbit:$TRAVIS_BUILD_NUMBER;
      fi;
      if [ "$TRAVIS_BRANCH" == "develop" ] || [ "$TRAVIS_BRANCH" == "master" ]; then
        docker tag nestal/hearty_rabbit nestal/hearty_rabbit:$TRAVIS_BRANCH;
      fi;
      docker push nestal/hearty_rabbit;
      echo "Pushed docker image to hub";
    fi;
