sudo: required
language: c++
services:
  - docker

before_install:
  - docker pull nestal/hearty_rabbit_dev
  - git submodule update --init --recursive

script:
  - make -f automation/Makefile BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
