#!/usr/bin/env bash

# Have this script to exit if any of the step below fails
set -e

# login and save cookie in /tmp/cookiejar
curl -v -Lk -c /tmp/cookiejar -b /tmp/cookiejar -d 'username=nestal&password=hello' -- https://localhost:4433/login

for TEST in ./tests/*;
do
	echo "Running test $TEST"
	source $TEST
done
