#!/usr/bin/env bash

# Find the root directory of the source code base on the location of this script
pushd "$( dirname "${BASH_SOURCE[0]}" )"/..
pwd

# Start server
docker run -t --detach --rm \
  -v $(pwd)/etc/hearty_rabbit:/etc/hearty_rabbit:ro \
  -v $(pwd)/lib:/lib:ro \
  -v /dev/log:/dev/log \
  -v /tmp:/tmp \
  --network=host --name hb_test \
    nestal/hearty_rabbit

# Run python unit tests
python3 ./unittest/client/upload_blob.py || { echo "auto system test failed!"; docker stop hb_test; exit 1}

# Run all tests
pushd automation
source ./run_tests

docker stop hb_test
