#!/usr/bin/env bash

# Find the root directory of the source code base on the location of this script
pushd "$( dirname "${BASH_SOURCE[0]}" )"/..
pwd

# Start server
docker run -t --detach --rm \
  -v $(pwd)/etc/hearty_rabbit:/etc/hearty_rabbit \
  -v $(pwd)/lib:/lib \
  --network=host --name hb_test \
    nestal/hearty_rabbit

# Run all tests
pushd automation
source ./run_tests

docker stop hb_test
