#!/usr/bin/env bash

#   Copyright © 2018 Wan Wai Ho <me@nestal.net>
#
#   This file is subject to the terms and conditions of the GNU General Public
#	License.  See the file COPYING in the main directory of the hearty_rabbit
#   distribution for more details.

# This script executes the automated API test suite of hearty rabbit.
# It first launch hearty rabbit in a docker container in the background, and then
# runs the python test suite.

# Find the root directory of the source code base on the location of this script
pushd "$( dirname "${BASH_SOURCE[0]}" )"/..
pwd

# Start server
docker run -t --detach --rm \
  -v $(pwd)/etc/hearty_rabbit:/etc/hearty_rabbit:ro \
  -v $(pwd)/lib:/lib:ro \
  -v /dev/log:/dev/log \
  -v /tmp:/tmp \
  --network=host --name hb_test \
    nestal/hearty_rabbit

# Run python unit tests
pushd testing/python
python3 api_tests.py || { echo "auto system test failed!"; docker stop hb_test; exit 1;}
popd

docker stop hb_test
